export enum CALL_OUTCOMES {
  PROMISED_TO_PAY = 'PROMISED_TO_PAY',
  PAYMENT_PLAN = 'PAYMENT_PLAN',
  PARTIAL_PAYMENT = 'PARTIAL_PAYMENT',
  FULL_PAYMENT = 'FULL_PAYMENT',
  NO_ANSWER = 'NO_ANSWER',
  CALL_BACK_LATER = 'CALL_BACK_LATER',
  REFUSED = 'REFUSED',
  DISPUTED = 'DISPUTED',
  UNREACHABLE = 'UNREACHABLE',
  NUMBER_INVALID = 'NUMBER_INVALID',
}
